import "@/_styles/globals.css";
import "@/_styles/reset.css";

import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import { ReactNode } from "react";
import combine_class from "@/_utils/combine_class";
import { themeClassName } from "@/_styles/global.css";
import Header from "@/_components/layout/Header";
import Footer from "@/_components/layout/Footer";

const noto_sans_kr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Chess",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        style={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}
        className={combine_class(noto_sans_kr.className, themeClassName)}
      >
        <Header />
        <main style={{ flex: 1 }}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
